#!/usr/bin/env bash
#
# convert.sh -- Convert Cletrics FinOps agent .md files into tool-specific formats.
#
# Reads all agent files from category directories and outputs converted files
# to integrations/<tool>/. Regenerate after adding or modifying agents.
#
# Usage:
#   ./scripts/convert.sh [--tool <name>] [--help]
#
# Tools:
#   cursor     -- Cursor rule files (.mdc)
#   windsurf   -- Single .windsurfrules bundling all agents
#   aider      -- Single CONVENTIONS-finops.md bundling all agents
#   opencode   -- OpenCode agent files
#   all        -- All tools (default)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$REPO_ROOT/integrations"

AGENT_DIRS=(
  cloud-cost commitments kubernetes data-platforms governance waste-detection specialized
)

usage() { sed -n '3,18p' "$0" | sed 's/^# \{0,1\}//'; exit 0; }

get_field() {
  awk -v f="$1" '
    /^---$/ { fm++; next }
    fm == 1 && $0 ~ "^" f ": " { sub("^" f ": ", ""); print; exit }
  ' "$2"
}

get_body() { awk 'BEGIN{fm=0} /^---$/{fm++; next} fm>=2{print}' "$1"; }

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//'
}

convert_cursor() {
  local file="$1"
  local name description slug outfile body
  name="$(get_field "name" "$file")"
  description="$(get_field "description" "$file")"
  slug="$(slugify "$name")"
  body="$(get_body "$file")"
  outfile="$OUT_DIR/cursor/rules/${slug}.mdc"
  mkdir -p "$OUT_DIR/cursor/rules"
  cat > "$outfile" <<HEREDOC
---
description: ${description}
globs: ""
alwaysApply: false
---
${body}
HEREDOC
}

convert_opencode() {
  local file="$1"
  local name description slug outfile body
  name="$(get_field "name" "$file")"
  description="$(get_field "description" "$file")"
  slug="$(slugify "$name")"
  body="$(get_body "$file")"
  outfile="$OUT_DIR/opencode/agents/${slug}.md"
  mkdir -p "$OUT_DIR/opencode/agents"
  cat > "$outfile" <<HEREDOC
---
name: ${name}
description: ${description}
mode: subagent
---
${body}
HEREDOC
}

AIDER_TMP="$(mktemp)"
WINDSURF_TMP="$(mktemp)"
trap 'rm -f "$AIDER_TMP" "$WINDSURF_TMP"' EXIT

cat > "$AIDER_TMP" <<'HEREDOC'
# Cletrics FinOps Agents -- Aider Conventions
#
# Full roster of FinOps specialist agents. To activate an agent, reference it
# by name in your Aider session prompt, e.g.:
#   "Use the AWS Cost Explorer Analyst agent to audit this month's spend."
#
# Generated by scripts/convert.sh -- do not edit manually.

HEREDOC

cat > "$WINDSURF_TMP" <<'HEREDOC'
# Cletrics FinOps Agents -- Windsurf Rules
#
# Full roster. Reference an agent by name in Windsurf chat to activate it.
#
# Generated by scripts/convert.sh -- do not edit manually.

HEREDOC

accumulate_aider() {
  local file="$1" name description body
  name="$(get_field "name" "$file")"
  description="$(get_field "description" "$file")"
  body="$(get_body "$file")"
  cat >> "$AIDER_TMP" <<HEREDOC

---

## ${name}

> ${description}

${body}
HEREDOC
}

accumulate_windsurf() {
  local file="$1" name description body
  name="$(get_field "name" "$file")"
  description="$(get_field "description" "$file")"
  body="$(get_body "$file")"
  cat >> "$WINDSURF_TMP" <<HEREDOC

================================================================================
## ${name}
${description}
================================================================================

${body}

HEREDOC
}

run_conversions() {
  local tool="$1"
  local count=0 file first_line
  for dir in "${AGENT_DIRS[@]}"; do
    local dirpath="$REPO_ROOT/$dir"
    [[ -d "$dirpath" ]] || continue
    while IFS= read -r -d '' file; do
      first_line="$(head -1 "$file")"
      [[ "$first_line" == "---" ]] || continue
      [[ "$(basename "$file")" == "README.md" ]] && continue
      case "$tool" in
        cursor)   convert_cursor "$file" ;;
        opencode) convert_opencode "$file" ;;
        aider)    accumulate_aider "$file" ;;
        windsurf) accumulate_windsurf "$file" ;;
      esac
      (( count++ )) || true
    done < <(find "$dirpath" -name "*.md" -type f -print0 | sort -z)
  done
  echo "$count"
}

main() {
  local tool="all"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --tool)    tool="${2:?'--tool requires a value'}"; shift 2 ;;
      --out)     OUT_DIR="${2:?'--out requires a value'}"; shift 2 ;;
      --help|-h) usage ;;
      *)         echo "Unknown option: $1" >&2; usage ;;
    esac
  done

  local valid_tools=("cursor" "opencode" "aider" "windsurf" "all")
  local valid=false t
  for t in "${valid_tools[@]}"; do [[ "$t" == "$tool" ]] && valid=true && break; done
  if ! $valid; then echo "Unknown tool '$tool'. Valid: ${valid_tools[*]}" >&2; exit 1; fi

  local tools_to_run=()
  if [[ "$tool" == "all" ]]; then
    tools_to_run=("cursor" "opencode" "aider" "windsurf")
  else
    tools_to_run=("$tool")
  fi

  local total=0
  for t in "${tools_to_run[@]}"; do
    printf "Converting: %s\n" "$t"
    local count
    count="$(run_conversions "$t")"
    total=$(( total + count ))
    printf "  %s agents converted\n" "$count"
  done

  if [[ "$tool" == "all" || "$tool" == "aider" ]]; then
    mkdir -p "$OUT_DIR/aider"
    cp "$AIDER_TMP" "$OUT_DIR/aider/CONVENTIONS-finops.md"
    echo "Wrote integrations/aider/CONVENTIONS-finops.md"
  fi
  if [[ "$tool" == "all" || "$tool" == "windsurf" ]]; then
    mkdir -p "$OUT_DIR/windsurf"
    cp "$WINDSURF_TMP" "$OUT_DIR/windsurf/.windsurfrules"
    echo "Wrote integrations/windsurf/.windsurfrules"
  fi

  echo "Done. Total conversions: $total"
}

main "$@"
